onnx_path: "dance_0605.onnx"

motion_length: 18.0

kps: [100, 100, 100, 200, 20, 20,
            100, 100, 100, 200, 20, 20,
            400, 400, 400,
            90,   60,  20, 60, 20, 20, 20,
            90,   60,  20, 60, 20, 20, 20
            ]

kds: [2.5, 2.5, 2.5, 5.0, 0.2, 0.1,
            2.5, 2.5, 2.5, 5.0, 0.2, 0.1,
            5.0, 5.0, 5.0,
            2.0, 1.0, 0.4, 1.0, 0.4, 0.4, 0.4,
            2.0, 1.0, 0.4, 1.0, 0.4, 0.4, 0.4
            ]

tau_limit: [88, 88, 88, 139, 50, 50,
            88, 88, 88, 139, 50, 50,
            88, 50, 50,
            25, 25, 25, 25, 5, 5, 5,
            25, 25, 25, 25, 5, 5, 5
           ]

default_angles: [-0.1,  0.0,  0.0,  0.3, -0.2, 0.0, 
                 -0.1,  0.0,  0.0,  0.3, -0.2, 0.0,
                  0.0, 0.0, 0.0, 
                  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 
                  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0
                  ]

dof23_index: [ 0, 1, 2, 3, 4, 5,
               6, 7, 8 ,9 ,10, 11,
               12, 13, 14,
               15, 16, 17, 18,
               22, 23, 24, 25
             ]

ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
action_scale: 0.25
history_length: 4
num_actions: 23
num_obs: 380