policy_path: "policy_29dof.pt"

kps: [200, 200, 200,
      150, 150, 200,
      150, 150, 200,
      200, 200,      100, 100,
      20,  20,       100, 100,
      20,  20,       50,  50, 
                     50,  50,
                     40,  40,
                     40,  40,
                     40,  40]

kds: [5, 5, 5, 
      5, 5, 5, 
      5, 5, 5, 
      5, 5,     2, 2,
      2, 2,     2, 2, 
      2, 2,     2, 2,
                2, 2,
                2, 2,
                2, 2,
                2, 2]

tau_limit: [88, 88, 88, 139, 50, 50,
            88, 88, 88, 139, 50, 50,
            88, 50, 50,
            25, 25, 25, 25, 5, 5, 5,
            25, 25, 25, 25, 5, 5, 5
           ]

default_angles: [-0.2,  -0.2,  0.0,
                  0.0,   0.0,  0.0,
                  0.0,   0.0,  0.0, 
                  0.42,  0.42,       0.35,  0.35,
                 -0.23, -0.23,       0.18, -0.18, 
                  0.0,   0.0,        0.0,   0.0, 
                                     0.87,  0.87, 
                                     0.0,   0.0, 
                                     0.0,   0.0, 
                                     0.0,   0.0]

joint2motor_idx: [0, 6, 12, 
                  1, 7, 13, 
                  2, 8, 14, 
                  3, 9,      15, 22,
                  4, 10,     16, 23, 
                  5, 11,     17, 24, 
                             18, 25, 
                             19, 26, 
                             20, 27, 
                             21, 28]

cmd_scale: [1.0, 1.0, 1.0]
cmd_init: [0, 0, 0]
ang_vel_scale: 1.0
dof_pos_scale: 1.0
dof_vel_scale: 1.0
action_scale: 0.25
num_actions: 29
num_obs: 96
cmd_range: {lin_vel_x: [-0.4, 0.7], lin_vel_y: [-0.4, 0.4], ang_vel_z: [-1.57, 1.57]}

